name: Name of the workflow else relative path

on: [push, workflow_dispatch]
#This event will only trigger a workflow run if the workflow file exists on the default branch.

concurrency:
  group: workflow-concepts
  #This will cancel any in-progress runs of this workflow if a new run is triggered.
  #This is useful to prevent multiple runs of the same workflow from running at the same time
  #and consuming resources unnecessarily.
  #For example, if you push multiple commits in quick succession, only the latest commit will trigger a run.
  #This is useful for workflows that are triggered by push events, such as CI/CD workflows.
  #If you want to allow multiple runs of the same workflow to run at the same time,
  #you can remove this concurrency setting or set `cancel-in-progress` to false.  
  cancel-in-progress: true
run-name: Installer test
env:
  WORKFLOW_LEVEL: workflow
  JOB_LEVEL_VAR: job1
  STEP_LEVEL_VAR: step2
jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
     contents: read
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
            path: core
            fetch-depth: 0

        - name: Just Listing with multiline
          run: |
            echo "Just Echoing"
            ls -ltra core
            echo "------------"
            ls ../
            echo ${{ env.WORKFLOW_LEVEL }}
            echo ${{ env.JOB_LEVEL_VAR }}
            echo ${{ env.STEP_LEVEL_VAR }}
        - name: install and run figlet
          run: | 
           chmod +x ./core/scripts/installer.sh
           ./core/scripts/installer.sh ${{ secrets.password1 }}
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Piglet
            path: abc.txt

  download_artifact:
        runs-on: ubuntu-latest
        needs: first_job
        env:
          JOB_LEVEL_VAR: job
          STEP_LEVEL_VAR: step1
        steps:
            - name: Download the Artifact
              uses: actions/download-artifact@v4
              with:
                name: Piglet
            - name: Read the Artifact
              env:
                STEP_LEVEL_VAR: step
              run: |
                cat abc.txt
                echo ${{ env.STEP_LEVEL_VAR }}
                echo ${{ env.JOB_LEVEL_VAR }}
                echo ${{ env.WORKFLOW_LEVEL }}
                echo $STEP_LEVEL_VAR
                echo $JOB_LEVEL_VAR
                echo $WORKFLOW_LEVEL
                echo ${{ vars.REPO_LVL_VAR }}


        




