name: Name of the workflow else relative path

on: [push]
run-name: Installer test
env:
  WORKFLOW_LEVEL: workflow
  JOB_LEVEL_VAR: job1
  STEP_LEVEL_VAR: step2
jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
     contents: read
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
            path: core
            fetch-depth: 0

        - name: Just Listing with multiline
          run: |
            echo "Just Echoing"
            ls -ltra core
            echo "------------"
            ls ../
            echo ${{ env.WORKFLOW_LEVEL }}
            echo ${{ env.JOB_LEVEL_VAR }}
            echo ${{ env.STEP_LEVEL_VAR }}
        - name: install and run figlet
          run: | 
           chmod +x ./core/scripts/installer.sh
           ./core/scripts/installer.sh ${{ secrets.password1 }}
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Piglet
            path: abc.txt

  download_artifact:
        runs-on: ubuntu-latest
        needs: first_job
        env:
          JOB_LEVEL_VAR: job
          STEP_LEVEL_VAR: step1
        steps:
            - name: Download the Artifact
              uses: actions/download-artifact@v4
              with:
                name: Piglet
            - name: Read the Artifact
              env:
                STEP_LEVEL_VAR: step
              run: |
                cat abc.txt
                echo ${{ env.STEP_LEVEL_VAR }}
                echo ${{ env.JOB_LEVEL_VAR }}
                echo ${{ env.WORKFLOW_LEVEL }}
                echo $STEP_LEVEL_VAR
                echo $env.JOB_LEVEL_VAR
                echo $env.WORKFLOW_LEVEL
                echo ${{ vars.REPO_LVL_VAR }}


        




